import type { CardTheme } from "../consts";

export const DEFAULT_KNOWLEDGE_CARD_THEME = "blackWhite";

export const KNOWLEDGE_CARD_THEME: Record<string, CardTheme> = {
  blackWhite: {
    textColor: "#000000",
    backgroundClass: "black-white",
    accentColor: "#000000",
    borderColor: "#e5e5e5",
    subtleColor: "#666666",
    decorativeLineColor: "#000000",
    numberColor: "#000000",
    backgroundColor: "#ffffff",
    titleColor: "#000000",
    titleFontSize: "clamp(24px, 4vw, 32px)",
    titleFontWeight: "bold",
    descriptionColor: "#666666",
    descriptionFontSize: "16px",
    sectionTitleColor: "#000000",
    sectionTitleFontSize: "20px",
    sectionTitleFontWeight: "600",
    keyPointColor: "#000000",
    keyPointFontSize: "14px",
    numberBackgroundColor: "#000000",
    numberTextColor: "#ffffff",
    numberFontWeight: "bold",
    decorativeLineWidth: "4px",
    decorativeLineHeight: "80px",
    linkColor: "#000000",
  },
  vintage: {
    textColor: "#3D2914",
    backgroundClass: "vintage",
    accentColor: "#8B4513",
    borderColor: "#D2B48C",
    subtleColor: "#8B7355",
    decorativeLineColor: "#8B4513",
    numberColor: "#3D2914",
    backgroundColor: "#FAF0E6",
    gradient: "linear-gradient(135deg, #faf0e6 0%, #f5e6d3 50%, #ffefd5 100%)",
    titleColor: "#2F1B14",
    titleFontSize: "clamp(26px, 4vw, 34px)",
    titleFontWeight: "bold",
    titleFontFamily: "'Playfair Display', 'Georgia', 'Times New Roman', serif",
    descriptionColor: "#5D4E37",
    descriptionFontSize: "16px",
    descriptionFontFamily: "'Crimson Text', 'Georgia', serif",
    sectionTitleColor: "#3D2914",
    sectionTitleFontSize: "20px",
    sectionTitleFontWeight: "600",
    sectionTitleFontFamily:
      "'Playfair Display', 'Georgia', 'Times New Roman', serif",
    keyPointColor: "#4A3728",
    keyPointFontSize: "14px",
    keyPointFontFamily: "'Crimson Text', 'Georgia', serif",
    numberBackgroundColor: "#8B4513",
    numberTextColor: "#FAF0E6",
    numberFontWeight: "bold",
    numberFontFamily: "'Playfair Display', 'Georgia', 'Times New Roman', serif",
    decorativeLineWidth: "5px",
    decorativeLineHeight: "85px",
    fontFamily: "'Crimson Text', 'Georgia', serif",
    linkColor: "#3D2914",
  },
  glassmorphism: {
    textColor: "#ffffff",
    backgroundClass: "glassmorphism",
    accentColor: "#60a5fa",
    borderColor: "rgba(255, 255, 255, 0.15)",
    subtleColor: "rgba(255, 255, 255, 0.8)",
    decorativeLineColor: "#60a5fa",
    numberColor: "#ffffff",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    backgroundImage: "/cards/glass.webp",
    titleColor: "#ffffff",
    titleFontSize: "clamp(24px, 4vw, 32px)",
    titleFontWeight: "bold",
    descriptionColor: "rgba(255, 255, 255, 0.95)",
    descriptionFontSize: "16px",
    sectionTitleColor: "#ffffff",
    sectionTitleFontSize: "20px",
    sectionTitleFontWeight: "600",
    keyPointColor: "rgba(255, 255, 255, 0.95)",
    keyPointFontSize: "14px",
    numberBackgroundColor: "rgba(96, 165, 250, 0.3)",
    numberTextColor: "#ffffff",
    numberFontWeight: "bold",
    decorativeLineWidth: "4px",
    decorativeLineHeight: "80px",
    linkColor: "#ffffff",
  },
  freshNature: {
    textColor: "#1f2937",
    backgroundClass: "fresh-nature",
    accentColor: "#22c55e",
    borderColor: "rgba(255, 255, 255, 0.3)",
    subtleColor: "#4a7c59",
    decorativeLineColor: "#22c55e",
    numberColor: "#1f2937",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    backgroundImage: "/cards/fresh.webp",
    titleColor: "#1f2937",
    titleFontSize: "clamp(24px, 4vw, 32px)",
    titleFontWeight: "bold",
    descriptionColor: "#1f2937",
    descriptionFontSize: "16px",
    sectionTitleColor: "#1f2937",
    sectionTitleFontSize: "20px",
    sectionTitleFontWeight: "600",
    keyPointColor: "#1f2937",
    keyPointFontSize: "14px",
    numberBackgroundColor: "#22c55e",
    numberTextColor: "#ffffff",
    numberFontWeight: "bold",
    decorativeLineWidth: "4px",
    decorativeLineHeight: "80px",
    linkColor: "#1f2937",
  },
};
